on:
  workflow_call:
    inputs:
      public_key:
        type: string
        required: true
      secret_value:
        type: string
        required: true
    outputs:
      encrypted_value:
        value: ${{ jobs.encrypt.outputs.encrypted_value }}
jobs:
  encrypt:
    name: Encrypt Secret
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: aaurizon/action
          path: _reusableaction
      - uses: actions/setup-python@v4
      - run: pip install pynacl
      - id: encrypt
        run: |
          ENCRYPTED_VALUE=$(python ./_reusableaction/.github/workflows/gh-encrypt-secret.py)
          echo "encrypted_value=$ENCRYPTED_VALUE" >> "$GITHUB_OUTPUT"
        env:
          PUBLIC_KEY: ${{ inputs.public_key }}
          SECRET_VALUE: ${{ inputs.secret_value }}
    outputs:
      encrypted_value: ${{ steps.encrypt.outputs.encrypted_value }}