on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      value:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true
jobs:
  public_key:
    name: Get Public Key
    runs-on: ubuntu-latest
    steps:
      - id: get_public_key
        run: |
          RESPONSE=$(gh api /repos/${{ github.repository }}/actions/secrets/public-key)
          KEY_ID=$(echo $RESPONSE | jq -r '.key_id')
          KEY=$(echo $RESPONSE | jq -r '.key')
          echo "key_id=$KEY_ID" >> "$GITHUB_OUTPUT"
          echo "key=$KEY"       >> "$GITHUB_OUTPUT"
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      key_id: ${{ steps.get_public_key.outputs.key_id }}
      key: ${{ steps.get_public_key.outputs.key }}
  encrypt:
    name: Encrypt Secret Value
    needs: public_key
    uses: ./.github/workflows/encrypt-secret.yaml
    with:
      public_key: ${{ needs.public_key.outputs.key }}
      secret_value: ${{ inputs.value }}
  set:
    name: Set Secret
    needs: [public_key, encrypt]
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api --method PUT /repos/${{ github.repository }}/actions/secrets/${{ inputs.name }} \
            -f encrypted_value="${{ needs.encrypt.outputs.encrypted_value }}" \
            -f key_id="${{ needs.public_key.outputs.key_id }}"
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}