on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      value:
        type: string
        required: true
      visibility:
        type: string
        required: true
        default: all
      selection:
        type: string
        default: ""
    secrets:
      TOKEN:
        required: true
jobs:
  set:
    name: Set Variable
    runs-on: ubuntu-latest
    steps:
      - name: Isset Variable
        run: |
          gh api --method GET /orgs/${{ github.repository_owner }}/actions/variables/${{ inputs.name }}
          if [ $? -eq 0 ]; then
            echo "ISSET=true" >> "$GITHUB_ENV"
          fi
        continue-on-error: true
      - name: Create Variable
        if: ${{ !env.ISSET }}
        run: |
          gh api --method POST /orgs/${{ github.repository_owner }}/actions/variables \
            -f name='${{ inputs.name }}' \
            -f value="${{ inputs.value }}" \
            -f visibility="${{ inputs.visibility }}"
      - name: Update Variable
        if: ${{ env.ISSET }}
        run: |
          gh api --method PATCH /orgs/${{ github.repository_owner }}/actions/variables/${{ inputs.name }} \
            -f name='${{ inputs.name }}' \
            -f value="${{ inputs.value }}" \
            -f visibility="${{ inputs.visibility }}"
    env:
      GH_TOKEN: ${{ secrets.TOKEN }}