on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true
jobs:
  unset:
    runs-on: ubuntu-latest
    steps:
      - run : gh api --method DELETE /repos/${{ github.repository }}/actions/variables/${{ inputs.name }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}