on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      environment:
        type: string
        required: true
    secrets:
      GH_TOKEN:
        required: true
jobs:
  unset:
    runs-on: ubuntu-latest
    steps:
      - run : gh api --method DELETE /repositories/${{ github.repository_id }}/environments/${{ inputs.environment }}/secrets/${{ inputs.name }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}