on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      organization:
        type: string
        required: false
    secrets:
      GH_TOKEN:
        required: true
jobs:
  unset:
    runs-on: ubuntu-latest
    steps:
      - run : gh api --method DELETE /orgs/${{ inputs.organization || github.repository_owner }}/actions/variables/${{ inputs.name }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}